### ISSUE TITLE
Close button issue

### ISSUE THREAD

**Issue by ray73864** [KaneCohen/modal-vanilla#10]
For some reason, my close button doesn't look like an 'x', it shows as a weird 'a' character.

![modal-vanilla-close-button-issue](https://user-images.githubusercontent.com/1343103/61848973-5eedde80-aee2-11e9-9db1-6c3922300bf9.png)

**Comment by KaneCohen** [comment]
Are you somehow prepossessing library JS? Webpack, gulp or something else? That "x" character is added as unicode character [here](https://github.com/KaneCohen/modal-vanilla/blob/master/dist/modal.js#L172) so maybe preprocessor has some issues.

**Comment by ray73864** [comment]
I am not, no. I'm just adding it to my page via the <script> tag.

Basically I downloaded the .tar.gz from github, extracted it out to my webserver, and updated my webpage to include the modal.min.js file on it.

**Comment by KaneCohen** [comment]
Check your HTML on the page - do you have `<meta charset="utf-8">` somewhere at the top? Maybe browser tries to interpret encoding differently.

**Comment by ray73864** [comment]
I do, yes.

**Comment by KaneCohen** [comment]
Check your file "modal.min.js" - does it have that "x" symbol in it? Maybe when extracting file something was changed in an encoding.

You could also try downloading file from here: <https://raw.githubusercontent.com/KaneCohen/modal-vanilla/master/dist/modal.min.js>

**Comment by ray73864** [comment]
Fixed the issue. The minified file was fine, it had the 'x' in it, but when the browser was bringing everything in, it wasn't pulling the JS file in properly.

Added charset="UTF-8" to the <script> tag and now the 'x' shows correctly.
