### ISSUE TITLE
Modal classes - Add additional

### ISSUE THREAD

**Issue by ray73864** [KaneCohen/modal-vanilla#11]
One part of my site has a dark theme, but I need the modals to be light themed, is there anyway (besides in the 'show' event) of adding additional classes to the modal?

I also have a need for some of the modals to be wider, such as 1000px wide.

**Comment by KaneCohen** [comment]
All of the styling for the Modal happens entirely in CSS. In your page you probably load bootstrap.css right? You'll need to add additional styles to make Modal look dark or increase its width.

This library bases its HTML on similar popup library in Bootstrap, that way if you modify bootstrap CSS it will affect the way modal looks.

**Comment by ray73864** [comment]
Yeah.

What I did is: 
```
this.el.classList.add("modal-wide");
this.el.classList.querySelector(".modal-content").classList.add("bg-light");
this.el.classList.querySelector("button.close").classList.add("text-dark");
```
Not every modal is going to be the same. 
The website is an internal company one, on this particular page (the bosses ordering system which uses a dark theme), he has modals where some are dark, some are light, some are wide (1800px, 1600px, and 1000px), and some that are just small ones.

So unfortunately it is either pass the classnames via an option when creating the modal (which is what I used to do with BootboxJS, but bootboxjs requires jQuery, and i'm basically getting rid of it), or do what I have done which is on the 'show' event, add the extra classes.

**Comment by KaneCohen** [comment]
This is the list of templates modal use:

```js

const _templates = {
  container: '<div class="modal"></div>',
  dialog: '<div class="modal-dialog"></div>',
  content: '<div class="modal-content"></div>',
  header: '<div class="modal-header"></div>',
  headerClose: '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>',
  body: '<div class="modal-body"></div>',
  footer: '<div class="modal-footer"></div>',
  backdrop: '<div class="modal-backdrop"></div>'
};
```

Each item can be overriten globally or for one instance.

If you want to override some class globally add this somewhere on the page (but after modal.js is loaded):

```js
Modal.templates = {
  dialog: '<div class="modal-dialog custom-classs"></div>',
};
```
This will override only `dialog` part. The rest will stay as default.

Alternatively you can pass custom class to the instance:

```js
new Modal({
templates: {
    dialog: '<div class="modal-dialog custom-classs"></div>',
}});
```

**Comment by KaneCohen** [comment]
Note - described above only works for "constructed" Modals. If you have fully done modal HTML on the page - you'll have to modify html on the page. Changing `templates` won't affect those.

**Comment by ray73864** [comment]
Ahh, awesome, thanks for that.

Will come in great handiness, certainly saves having to query the DOM.

Yeah, not an issue with that, all modals are pre-stylised (by JS if need be) before it shows on the screen. Once displayed it'll never change how it looks.

**Comment by ray73864** [comment]
One more thing, is there any chance of getting the title added to the templates?

In 1 particular modal window I need to add 'w-100' to the titles classes so that I can 'float: left' and 'float: right' some content.
