### ISSUE TITLE
Prompt Modal

### ISSUE THREAD

**Issue by ray73864** [KaneCohen/modal-vanilla#12]
Is there any easy way of creating a prompt?

I realise it is easy to do via new Modal() and setting everything I want, just wondering if there is any future plans to add prompts to the library?

**Comment by KaneCohen** [comment]
Depends on what you expect from prompt. Modal already has confirm/alert type of functionality. You can see examples here: <https://kanecohen.github.io/modal-vanilla/>

**Comment by ray73864** [comment]
Just needs a single text box on it, and when a person presses return on the text box, it dismisses the modal and allows you in the 'dismiss' event to get the value that was put into the text box.

The way I am planning to do it at present is to have a form on the modal with a single text box, listen for the enter key, when it is pressed, trigger the 'click' event on the OK button and then in the dismiss event get the value (assuming the content of the modal is still available in the dismiss event).

**Comment by KaneCohen** [comment]
As shown in the examples link above:

```js
 var confirmModal = Modal.confirm('My Custom Alert');
  confirmModal.show().once('dismiss', function(modal, ev, button) {
    if (button && button.value) {
      alert("You've clicked on an OK button.");
    }
  });
```

**Comment by ray73864** [comment]
I figured out what I needed.

It isn't pretty, but:

```
    const rand1 = Math.floor(Math.random() * 11);
    const rand2 = Math.floor(Math.random() * 11);

    let keyPressEventHandler = function(e, modal) { 
        if ( e.keyCode === 13 ) { 
          e.preventDefault();
          e.stopPropagation();
          modal.emit('dismiss', this, e, e.target);
        } 
      };

      new Modal({
        title: "Confirm Action",
        content: 'Answer to ' rand1 '+' + rand2 +
                 '<br>' +
                 '<form class="modal-form" autocomplete="off">' +
                   '<input type="text" class="modal-input modal-input-text form-control">' +
                 '</form>'
      }).on("shown", function(e) { 
        this.el.querySelecotr(".modal-input").addEventListener("keypress", function(e) { keyPressEventHandler(e, modal); });
      }).on("dismiss", function(modal, e, btn) {  
        if ( btn.value !== "" && app.isNumeric(btn.value) && Number(btn.value) === rand1 + rand2 ) { this.hide(); confirmAction(); } else { this.hide(); }
      }).show();
```
As said, it's not pretty, but it does work. The most difficult part was working out the 'emit()' function.

Basically this is for a 'delete' action, the boss a long time ago wanted me to create a 3 stage delete system.

Stage 1 has a prompt dialog which asks him a math question.
Stage 2 has a confirm dialog which asks him if he is sure.
Stage 3 has a prompt dialog which again asks him if he is sure by inputting either a "Y" or an "N".

If he answers "Y" to stage 3, then the system goes and performs the action, which could be an AJAX request telling the backend to delete a record from the database.

We went this way with the deletion because according to him, when he's tired, he has trouble answering the math question and so can't accidentally delete something.

Stage 2 is easy because this library already has 'confirm' dialogs, it was just Stage 1 and 3 I had to deal with where I needed a dialog with a textbox on it, and when the dialog is dismissed (by pressing the enter key, or clicking on OK, or cancelling the dialog) get the textbox value and check it to see if the final action should be run.
