### ISSUE TITLE
Modal focus

### ISSUE THREAD

**Issue by ray73864** [KaneCohen/modal-vanilla#14]
Is there any way to give the modal the focus when it gets opened?

I have an input box on my main page which has the focus, I press a function key on the keyboard "F10" for instance which opens the modal, but the input box still has the focus, I then can't add eventlisteners to the modal for keydown because the modal never has the focus.

If I click on the modal to give it focus, the eventlisteners still don't trigger (But that's my problem to work out).

I have tried setting the focus to the modal in the 'shown' event to no avail.

The thing that would probably make this easier is if everything behind the overlay (so basically anything not the modal) couldn't respond to any event at all.

NB: I have the header and the footer turned off, as for this particular modal they aren't supposed to be there.

**Comment by KaneCohen** [comment]
@ray73864 add an event listener to your modal instance where you can set focus to an element you need:

```js
modalInstance.on('shown', function() {
  // Focus on some element here
}).show();
```
