### ISSUE TITLE
Question: How do we use this after we pull ? which js file do we import in html? do we have detailed instructions on first usage apart from README?

### ISSUE THREAD

**Issue by pavnvar** [KaneCohen/modal-vanilla#19]

**Comment by KaneCohen** [comment]
Depending on your usecase - you can either just do `import Modal from 'modal-vanilla';` or use `modal.min.js` file from `dist/` folder.

You can check source code of the [demo website](https://kanecohen.github.io/modal-vanilla/) to see how it's being loaded and used.
