### ISSUE TITLE
"TypeError: document.body is null" when included in <head>

### ISSUE THREAD

**Issue by JasonBarnabe** [KaneCohen/modal-vanilla#20]
I'm trying to use this in my Rails app through webpacker. The JS is included in a single reference in `<head>`. When I include modal-vanilla, I get `Uncaught TypeError: document.body is null`. Simplified test case:

```html
<html>
	<head>
		<script src="https://kanecohen.github.io/modal-vanilla/js/modal.min.js"></script>
	</head>
	<body>
	</body>
</html>
```

```
Uncaught TypeError: document.body is null
    _ https://kanecohen.github.io/modal-vanilla/js/modal.min.js:1
    Modal https://kanecohen.github.io/modal-vanilla/js/modal.min.js:1
    t https://kanecohen.github.io/modal-vanilla/js/modal.min.js:1
    Modal https://kanecohen.github.io/modal-vanilla/js/modal.min.js:1
    <anonymous> https://kanecohen.github.io/modal-vanilla/js/modal.min.js:1
modal.min.js:1:2605
```

**Comment by KaneCohen** [comment]
Looks like if script is included in the "head" part body is not yet available, so it fails. I would recommend loading external JS libraries at the bottom of the page, before `</body>` tag.

**Comment by JasonBarnabe** [comment]
Not really possible in my situation - all my other scripts are expecting to be in `<head>`.

It looks like it's just trying to get the width of the page - could it not add a DOMContentLoaded event listener if document.body is not set and just do it later?

**Comment by KaneCohen** [comment]
Moved page scroll width detection into the class itself - use `v0.9.0` to get latest code.
