### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mcdoolz** [KaneCohen/modal-vanilla#21]
When attempting to use require() within my node application, I'm receiving this error; using the dist version of the js works fine.
I installed the library using --save-dev but had no luck.

**Comment by mustafa-kapadia1483** [comment]
Adding `"type": "module"` to package.json should fix that

**Comment by KaneCohen** [comment]
@mustafa-kapadia1483 done in `v0.11.0`.
