### ISSUE TITLE
Modal closes when mouse click is released outside the modal

### ISSUE THREAD

**Issue by GastonZalba** [KaneCohen/modal-vanilla#22]
The modal closes when a `click` event is fired after releasing the button outside the modal. This behavior is very annoying if you are trying to select a text inside the modal,  dragging the cursor and releasing it outside.

This can be fixed using a `pointerdown` event (and checking that only the left click was used) instead of the `click`. I can make a PR if it helps.

Thanks!

Example:
![modal-bug](https://user-images.githubusercontent.com/34213485/167262330-387d9ad9-ca9d-4f2b-a077-9eb3ff3c5e53.gif)

**Comment by KaneCohen** [comment]
Hi, thanks for the info.

If you could - do submit PR. if not - I'll look over it over the next week.

**Comment by KaneCohen** [comment]
Hi, thanks for the PR, but it the way stuff worked wasn't quite the same as normal Bootstrap modal. I've pushed v0.10.0 with updated code which tracks if mouse event originated from within the content of the modal and prevent hiding from triggering.

Again, thanks for the info and the PR.
