### ISSUE TITLE
v0.11.0 breaks on webpack

### ISSUE THREAD

**Issue by GastonZalba** [KaneCohen/modal-vanilla#24]
Hi, the version `v0.11.0` and the addition of `"type": "module"` (suggested in #21) now throws error using webpack.

Using:
`import Modal from 'modal-vanilla';`

Throws error:
`export 'default' (imported as 'Modal') was not found in 'modal-vanilla' (module has no exports)`

**Comment by KaneCohen** [comment]
@GastonZalba i'll look into this. These modules and compatibility with old and new require/import stuff is rather confusing.

**Comment by KaneCohen** [comment]
@GastonZalba deployed 0.12.0. Tested it locally and seems to be working. Would appreciate if you could test in your environment.

**Comment by GastonZalba** [comment]
@KaneCohen v0.12.0 works perfectly!
