### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by dotmagic** [KaneCohen/modal-vanilla#4]
Actually the Javascript code in dist/ still contains Object.assign() which is not supported in IE11, can you tweak your webpack config to make it compatible with IE11?

https://babeljs.io/docs/plugins/transform-object-assign/

It may be properly better to just use pure babel and only imports so webpack won't be required and the javascript code is even more vanilla :)

**Comment by KaneCohen** [comment]
Thanks for the report, I'll look into that.

**Comment by dotmagic** [comment]
Just want to give a update. I did create a fork and done the changes mention above. But I still found some other issues, you're using some dom4 methods not available in IE11, i think it should be easy to rewrite this parts for including a polyfill. I will create a pull request today.

**Comment by KaneCohen** [comment]
Should be resolved in latest version.
