### ISSUE TITLE
create an alert in JS

### ISSUE THREAD

**Issue by yarekc** [KaneCohen/modal-vanilla#6]
I got that script with some static modals (that works ok)

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-modal/1.6.5/index.min.js"></script>
<script>var Modal = new VanillaModal.default();</script>
```

How do I display an alert like

`Modal .alert('My Custom Alert').show();`

SOmething similar to 
bootboxjs.alert('My Custom Alert') ?

regards

**Comment by KaneCohen** [comment]
I'm not quite sure what you mean, to be honest.

In first code block you load this library: "https://github.com/benceg/vanilla-modal" which is different from my library. First one is `Vanilla Modal` and this one is `Modal Vanilla`.

I'm not sure if `Vanilla Modal` supports `.alert()` functionality.

In case of my library - you just load minified (that's the one that is ready to use in the web) script and use it as you describe yourself in second. Example here: <https://jsfiddle.net/28Lmcd9p/>
