### ISSUE TITLE
Header rendering issue with Bootstrap 4

### ISSUE THREAD

**Issue by jeromelebleu** [KaneCohen/modal-vanilla#8]
It seems that header elements' order has changed with Bootstrap 4. The close button must now be the last child of `.modal-header` (see the documentation of [v3](https://getbootstrap.com/docs/3.3/javascript/#static-example) and [v4](https://getbootstrap.com/docs/4.2/components/modal/#modal-components)). It results in the following rendering issue:

![modal-header](https://user-images.githubusercontent.com/3597194/52066814-94d88880-2579-11e9-984a-3616707a1c65.png)

Unfortunately, it seems that this new order is also not compatible with Bootstrap 3... How to fix that? Could it be managed by the library itself?

By the way, thanks for your awesome work!

**Comment by KaneCohen** [comment]
@jeromelebleu hi. Thanks for the report.

I updated library to version `0.7.0` which has close button going after the modal-title.
Just update the version and run `npm install`.

**Comment by jeromelebleu** [comment]
Thanks a lot for your responsiveness!!

What do you think about specify the supported Bootstrap version in the README? And as a workaround for Bootstrap 3, adding `float: left;` to `.modal-title` should do the trick...
