### ISSUE TITLE
There's a error on 'import EventEmitter'

### ISSUE THREAD

**Issue by claudiocantara** [KaneCohen/modal-vanilla#9]
Hello, 
For some reason your lib is giving this error: 
```>> /myPathDirectory/node_modules/modal-vanilla/lib/modal.js:7
>> import EventEmitter from 'events';
>> ^
>> ParseError: 'import' and 'export' may appear only with 'sourceType: module'```

I think its about Babel.

**Comment by KaneCohen** [comment]
How are you using the library? Do you import it and then compile js or directly use in browser?

**Comment by claudiocantara** [comment]
Im using it inside my project, i tried to import and console show this error.

**Comment by claudiocantara** [comment]
Well i find out what is wrong.
I am using browserify with babelify and babel 7.
babelify haven't full suport to babel 7, i needed use option 'global' as true, so babel pass through node_modules. 

Thank you.
